# The definition of all endpoints that are autogenerated in WiseHomex

endpoints = [
  %{
    endpoints: [:index, :show, :create, :update, :delete],
    name_plural: "expenses",
    name_singular: "expense",
    path: "/expenses",
    type: "expenses"
  }
]
