defmodule WiseHomex.Creator do
  @moduledoc """
  Auto creation of main wise_homex module functions from configuration

  These function simply delegate to the api_client() function, which in turn sends a request to either
  the API client implementation or the mock server
  """

  @doc """
  When used by a module, we inject autogenerated mock functions from the api client definition
  """
  defmacro __using__([]) do
    WiseHomex.ApiDefinition.api_definition()
    |> WiseHomex.ApiDefinition.to_api_resources()
    |> Enum.map(&WiseHomex.Creator.create_endpoint/1)
  end

  @doc """
  Create a mock index function
  """
  def create_endpoint({:index, api_resource}) do
    function_name = "get_#{api_resource.name_plural}" |> String.to_atom()

    quote do
      def unquote(function_name)(config, query \\ %{}), do: api_client().unquote(function_name)(config, query)
    end
  end

  @doc """
  Create a mock show function
  """
  def create_endpoint({:show, api_resource}) do
    function_name = "get_#{api_resource.name_singular}" |> String.to_atom()

    quote do
      def unquote(function_name)(config, id, query \\ %{}), do: api_client().unquote(function_name)(config, id, query)
    end
  end

  @doc """
  Create a mock create function
  """
  def create_endpoint({:create, api_resource}) do
    function_name = "create_#{api_resource.name_singular}" |> String.to_atom()

    quote do
      def unquote(function_name)(config, attrs, rels),
        do: api_client().unquote(function_name)(config, attrs, rels)
    end
  end

  @doc """
  Create a mock update function
  """
  def create_endpoint({:update, api_resource}) do
    function_name = "update_#{api_resource.name_singular}" |> String.to_atom()

    quote do
      def unquote(function_name)(config, id, attrs, rels \\ %{}),
        do: api_client().unquote(function_name)(config, id, attrs, rels)
    end
  end

  @doc """
  Create a mock delete function
  """
  def create_endpoint({:delete, api_resource}) do
    function_name = "delete_#{api_resource.name_singular}" |> String.to_atom()

    quote do
      def unquote(function_name)(config, id), do: api_client().unquote(function_name)(config, id)
    end
  end
end
